# Generated by Django 5.1.7 on 2025-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('topic', models.TextField()),
                ('speakers', models.CharField(max_length=300)),
                ('school', models.CharField(choices=[('all', 'All Schools'), ('bs', 'Business School'), ('site', 'School of IT & Engineering'), ('seogi', 'School of Energy & Oil and Gas'), ('sg', 'School of Geology'), ('ise', 'International School of Economics'), ('kma', 'Kazakhstan Maritime Academy'), ('sam', 'School of Applied Mathematics'), ('sce', 'School of Chemical Engineering')], max_length=10)),
                ('event_type', models.CharField(choices=[('lecture', 'Lecture'), ('master_class', 'Master Class'), ('competition', 'Competition'), ('cultural', 'Cultural'), ('volunteering', 'Volunteering')], max_length=20)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
            ],
        ),
    ]
